spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/many_realm
        username: root
        password: root123
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
server:
    port: 80